### ISSUE TITLE
Videos on https://juju.is/docs/microk8s-cloud are shown as links rather than a video preview

### ISSUE THREAD

**Issue by mthaddon** [canonical-web-and-design/juju.is#165]
The videos on https://juju.is/docs/microk8s-cloud are shown as links rather than a video preview. For example:

```
A model is a container for a set of related applications. That model represents resources needed for the applications within it, including compute, storage and network.

juju add-model testing
https://discourse.jujucharms.com/uploads/default/original/1X/88e808884b25f675bc59c067a6f0f4a842a831da.mp4

Difference from traditional clouds: There is no ‘default’ model provided on k8s clouds. Creating a model implies creating a Kubernetes namespace. Rather than pollute your cluster’s namespaces, Juju favours an explicit approach.
```

**Comment by nottrobin** [comment]
Since Discourse's Markdown  parser doesn't support `<video>`, there's no easy way to solve this, and so I don't think it's an issue we want to look into at this point.

I think the best way for you to solve this is to use https://asciinema.org/, as is done on [this page](https://juju.is/docs/getting-started-with-juju). Bear in mind that when linking to images you need to use an absolute URL for them to work in docs. (see https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/76)
