### ISSUE TITLE
Discourse only supports Level 0, 1, and 2, but we need 3 and 4 also. All should be properly nested.

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#371]
Currently we have:

Level 0: Left-aligned, bold. Line break before the next Level 0 block.
Level 1: Left-aligned, bold **if no link attached**.
Level 2: Indent.

For example:

```
**Level 0**
**Level 1** / Level 1
     Level 2
--------------------
**Level 0**
```

What we need, imo:

Level 0: Left-aligned, bold. Line break before the next Level 0 block.
Level 1: Indented. Better no default on bolding.
Level 2: More indented.
Level 3: Even more indented.
Level 4: Even more indented. 

For example:

```
**Level 0**
     Level 1
          Level 2
               Level 3
                    Level 4
---------------------------
**Level 0**
```

All the levels except the most embedded one should be collapsible.

**Comment by tmihoc** [comment]
> This is related with the work @danielmutis is doing.

Indeed. So I think we can close this issue (or mark it as resolved when the thing @danielmutis is working on is resolved).

**Comment by danielmutis** [comment]
The side navigation only supports levels 0-3 and if you need further levels of navigation please raise it with the UX team so that we can see if this problem can be solved in a different way. Deeper navigations are prone to breaking due to horizontal space constraints. 

Level 0 is meant to be a heading/title in the navigation, hence level 1 stays at the same level of indentation, and levels 2 and 3 have a deeper indentation. If you have any concerns about this, please raise them in the next docs+design meeting so we can discuss your needs @tmihoc
