### ISSUE TITLE
After clicking on Navigation title, the Navigation view jumps to the top 

### ISSUE THREAD

**Issue by tmihoc** [canonical-web-and-design/juju.is#408]
I'm not sure how to explain this more clearly, but I can demonstrate it. It's a big problem for longer Navigation tables.

**Comment by steverydz** [comment]
Hi @tmihoc. What part of the site does this refer to?

**Comment by steverydz** [comment]
If you're referring to the links in the side navigation, these open new pages so would be expected to jump back to the top of the page, or am I misunderstanding?

**Comment by tmihoc** [comment]
> If you're referring to the links in the side navigation, these open new pages so would be expected to jump back to the top of the page, or am I misunderstanding?

Yes, you want to jump back to the top of the page---on the _page_ view. The Navigation view should remain where it was, no? Otherwise, if you want to click on the next title in the Navigation you'll have to scroll down a lot, again.

**Comment by danielmutis** [comment]
Hi @tmihoc. I understand that what you are suggesting is to have a separate scroll position on the navigation than on the content of the page so that the position can be preserved when the user clicks on a new page. I think this would be quite a deep change in the way that the pages are coded, and we have concerns about how reliable this solution would be.

Could you please bring this up in our next docs sync so that we can discuss the needs and how it would be implemented?

**Comment by tmihoc** [comment]
> Could you please bring this up in our next docs sync so that we can discuss the needs and how it would be implemented?

OK, will do.

**Comment by steverydz** [comment]
In that case I'll close this issue as the solution will be a wider topic.
