### ISSUE TITLE
juju.is/docs should explain 500s from Discourse

### ISSUE THREAD

**Issue by jetpackdanger** [canonical-web-and-design/juju.is#83]
It'd be helpful if the 500 page for juju.is/docs could give a suitable hint if the 500 was caused by a problem talking to Discourse.

**Comment by nottrobin** [comment]
Thanks @jetpackdanger.

If it's a 500 it's probably because it was an unanticipated error - as errors we expect should hopefully be leading to more informative statuses (e.g. 503 - Discourse is down; 504 - Discourse took too long to respond; 502 - invalid response from Discourse).

Given that we don't know the nature of the error when a 500 happens, it's not generally considered good practice to expose the error message directly, as we could end up leaking secret information about our system which could be used to exploit it. The same would actually apply to a `502` for example - we can tell you that Discourse responded something we didn't understand, but we still shouldn't be passing on the exact error message.

Do you know under what circumstances you saw this 500? Because I think the correct thing to do here is identify what the problem was, and then make sure we are handling that scenario explicitly and communicating back to the user what happened if that specific thing goes wrong again.

I'm going to close this now, as I don't think we want to generally expose 500 error messages, but if you do have more information about the specific problem you encountered that means we should improve our code to handle it better, could you please file an issue about that [over here](https://github.com/canonical-web-and-design/canonicalwebteam.discourse-docs/issues/new)?
